### PR TITLE
feat: python 3.12

### PR DESCRIPTION
**Pull request by dtdang**
### What I did
feat: add support for Python 3.12
chore: update lint dependencies

fixes: #

### Checklist

- [ ] Passes all linting checks (pre-commit and CI jobs)
- [ ] New test cases have been added and are passing
- [ ] Documentation has been updated
- [ ] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) standard (will be automatically included in the changelog)

### CODE REVIEW

**Comment by antazoey** [comment]
@dtdang Figure out how to resolve the lint crisis:

```
Skipping .ipynb files as Jupyter dependencies are not installed.
You can fix this by running ``pip install "black[jupyter]"``
```

It looks like we need to accept another lint dependency for this plugn for jupyter files. Make sure it is listed in both setup.py and pre-commit yaml for black's deps!

**Review by Ninjagod1251 — APPROVED** [review]

**Review by antazoey — APPROVED** [review]

**Review by antazoey — APPROVED** [review]
I guess the jupyter thing wasnt needed?

**Comment by dtdang** [comment]
I guess the jupyter issue fixed itself. I'm not sure why the macos functional tests aren't working though.

**Comment by antazoey** [comment]
> I guess the jupyter issue fixed itself. I'm not sure why the macos functional tests aren't working though.

it is because i have to edit the GH settings to remove the macos-latest requirement and change to macos-12 requirement

**Pull request merged**
